# Generated by Django 5.2 on 2025-04-21 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapihogar', '0002_alter_pedido_options_pedido_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='technician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rapihogar.technician', verbose_name='tecnico'),
        ),
    ]
