# Generated by Django 5.2 on 2025-04-21 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapihogar', '0003_add_technician_default_to_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapihogar.technician', verbose_name='tecnico'),
        ),
    ]
