# Generated by Django 5.2 on 2025-04-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapihogar', '0004_change_technician_default_in_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='hours_worked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
