# Generated by Django 5.2 on 2025-04-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapihogar', '0005_alter_pedido_hours_worked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Order',
        ),
    ]
