# Generated by Django 5.2 on 2025-04-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapihogar', '0006_rename_pedido_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technician',
            options={'verbose_name': 'Tecnico', 'verbose_name_plural': 'Tecnicos'},
        ),
    ]
